models/Bill.php
<?php

namespace codigowww\yii2ecommerce\models;

use Yii;
use codigowww\yii2ecommerce\components\Cart;

/**
 * This is the model class for table "ecommerce_bill".
 *
 * @property int $id
 * @property int $user_id
 * @property int $type_id
 * @property int $coupon_id
 * @property int $payment_method_id
 * @property int $bill_info_id
 * @property string $transaction
 * @property string $currency
 * @property string $subtotal
 * @property string $shipping
 * @property string $tax
 * @property string $hash
 * @property string $total
 * @property string $refund
 * @property string $shipping_info
 * @property string $note
 * @property string $created_at
 * @property string $updated_at
 * @property string $payment_date
 * @property string $expire_at
 * @property int $status
 *
 * @property BillInfo $billInfo
 * @property Coupon $coupon
 * @property PayMethod $paymentMethod
 * @property BillType $type
 * @property BillItem[] $billItems
 */
class Bill extends \yii\db\ActiveRecord {

    const STATUS_CREATED = 0;
    const STATUS_PENDING = 1;
    const STATUS_SUCCESS = 2;
    const STATUS_FAIL = 3;
    const EVENT_BILL_SUCCESS = 'bill-success';
    const EVENT_BILL_PENDING = 'bill-pending';
    const EVENT_BILL_CREATED = 'bill-created';
    const EVENT_BILL_FAIL = 'bill-fail';

    /**
     * {@inheritdoc}
     */
    public static function tableName() {
        return 'ecommerce_bill';
    }

    public static function getStatus() {
        return [
            self::STATUS_CREATED,
            self::STATUS_PENDING,
            self::STATUS_SUCCESS,
            self::STATUS_FAIL
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
            [['user_id', 'type_id', 'coupon_id', 'payment_method_id', 'bill_info_id', 'status'], 'integer'],
            [['created_at', 'status'], 'required'],
            [['payment_method_id'], 'required', 'on' => 'checkout'],
            [['subtotal', 'shipping', 'total', 'refund', 'tax'], 'number'],
            [['shipping_info', 'note'], 'string'],
            [['created_at', 'updated_at', 'payment_date', 'expire_at'], 'safe'],
            [['transaction', 'hash'], 'string', 'max' => 255],
            [['currency'], 'string', 'max' => 3],
            [['bill_info_id'], 'exist', 'skipOnError' => true, 'targetClass' => BillInfo::className(), 'targetAttribute' => ['bill_info_id' => 'id']],
            [['coupon_id'], 'exist', 'skipOnError' => true, 'targetClass' => Coupon::className(), 'targetAttribute' => ['coupon_id' => 'id']],
            [['payment_method_id'], 'exist', 'skipOnError' => true, 'targetClass' => PayMethod::className(), 'targetAttribute' => ['payment_method_id' => 'id']],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => BillType::className(), 'targetAttribute' => ['type_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => Yii::t('ecommerce', 'ID'),
            'user_id' => Yii::t('ecommerce', 'User ID'),
            'type_id' => Yii::t('ecommerce', 'Type ID'),
            'hash' => Yii::t('ecommerce', 'Hash'),
            'coupon_id' => Yii::t('ecommerce', 'Coupon ID'),
            'payment_method_id' => Yii::t('ecommerce', 'Payment Method ID'),
            'bill_info_id' => Yii::t('ecommerce', 'Bill Info ID'),
            'transaction' => Yii::t('ecommerce', 'Transaction'),
            'currency' => Yii::t('ecommerce', 'Currency'),
            'subtotal' => Yii::t('ecommerce', 'Subtotal'),
            'shipping' => Yii::t('ecommerce', 'Shipping'),
            'tax' => Yii::t('ecommerce', 'Tax'),
            'total' => Yii::t('ecommerce', 'Total'),
            'refund' => Yii::t('ecommerce', 'Refund'),
            'shipping_info' => Yii::t('ecommerce', 'Shipping Info'),
            'note' => Yii::t('ecommerce', 'Note'),
            'created_at' => Yii::t('ecommerce', 'Created At'),
            'updated_at' => Yii::t('ecommerce', 'Updated At'),
            'expire_at' => Yii::t('ecommerce', 'Expire At'),
            'payment_date' => Yii::t('ecommerce', 'Payment Date'),
            'status' => Yii::t('ecommerce', 'Status'),
        ];
    }

    private function applyCoupon($coupon) {
        if (!is_null($this->coupon_id)) {
            //revert coupon
            if ($coupon->discount_type == Coupon::TYPE_PERCENT) {
                $this->subtotal = $this->subtotal + ($this->subtotal * (1 + $coupon->discount));
            } else if ($coupon->discount_type == Coupon::TYPE_VALUE) {
                $this->subtotal += $coupon->discount;
            }
        }
        if ($coupon->discount_type == Coupon::TYPE_PERCENT) {
            $this->subtotal = $this->subtotal - ($this->subtotal * $coupon->discount);
        } else if ($coupon->discount_type == Coupon::TYPE_VALUE) {
            $this->subtotal -= $coupon->discount;
        }
    }

    public function loadCart($cart) {
        $cart_items = $cart->getItems(Cart::ITEM_PRODUCT);




        foreach ($cart_items as $cart_item) {

            $model = $cart_item['item'];
            $billitem = new BillItem();
            $billitem->bill_id = $this->id;
            $billitem->name = $model->label;
            $billitem->price = $model->price;
            $billitem->quantity = $cart_item['quantity'];
            $billitem->ref_id = $model->id;
            $billitem->status = 0;
            if (!$billitem->save()) {
                die(print_r($billitem->errors));
                throw new \yii\base\ErrorException("Fail to save bill item");
            }
        }
        $this->subtotal = $cart->getTotal(Cart::ITEM_PRODUCT);
        $coupon = $cart->coupon;
        if (!is_null($coupon)) {
            $this->coupon_id = $coupon->id;
        }

        $cart->clear();
    }

    public function calculateSubTotal() {
        $this->subtotal = 0;
        foreach ($this->billItems as $billitem) {
            $this->subtotal += $billitem->price * $billitem->quantity;
        }
        $coupon = $this->coupon;
        if (!is_null($coupon))
            $this->applyCoupon($coupon);
    }

    public function calculateTax() {
        $ecommerce = Yii::$app->getModule('ecommerce');
        if ($ecommerce->tax && $ecommerce->tax > 0) {
            $this->tax = $this->subtotal * $ecommerce->tax;
        }
    }

    public function calculate() {
        $this->calculateSubTotal();
        $this->calculateTax();
        //$this->calculateShipping();
        $this->calculateTotal();
    }

    public function calculateTotal() {
        $this->total = $this->subtotal + $this->shipping + $this->tax;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillInfo() {
        return $this->hasOne(BillInfo::className(), ['id' => 'bill_info_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCoupon() {
        return $this->hasOne(Coupon::className(), ['id' => 'coupon_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPaymentMethod() {
        return $this->hasOne(PayMethod::className(), ['id' => 'payment_method_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType() {
        return $this->hasOne(BillType::className(), ['id' => 'type_id']);
    }

    public function getStatusText() {

        switch ($this->status) {
            case self::STATUS_CREATED: return Yii::t('ecommerce', 'Created');
            case self::STATUS_PENDING: return Yii::t('ecommerce', 'Pending');
            case self::STATUS_SUCCESS: return Yii::t('ecommerce', 'Success');
            case self::STATUS_FAIL: return Yii::t('ecommerce', 'Fail');
            default: return Yii::t('ecommerce', '?');
        }
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillItems() {
        return $this->hasMany(BillItem::className(), ['bill_id' => 'id']);
    }

    public function setCreatedAtTimestamp($timestamp = null) {
        if (is_null($timestamp))
            $timestamp = time();
        $this->created_at = date("Y-m-d H:i:s", $timestamp);
    }

    public function setUpdatedAtTimestamp($timestamp = null) {

        if (is_null($timestamp))
            $timestamp = time();
        $this->updated_at = date("Y-m-d H:i:s", $timestamp);
    }

    public function setPaymentDateTimestamp($timestamp = null) {

        if (is_null($timestamp))
            $timestamp = time();
        $this->payment_date = date("Y-m-d H:i:s", $timestamp);
    }

    public static function getByHash($hash) {
        return Bill::findOne(['hash' => $hash]);
    }

    public function getIdHash() {
        return md5($str);
    }

    public function beforeSave($insert) {
        if (!parent::beforeSave($insert)) {
            return false;
        }

        
        if ($insert) {
            
            $str=rand(); 
            $this->hash = md5(Yii::$app->id . $this->currency .$str. time() .$this->created_at);
        }
        return true;
    }

}

models/BillType.php
<?php

namespace codigowww\yii2ecommerce\models;

use Yii;
use yii\helpers\ArrayHelper;
/**
 * This is the model class for table "ecommerce_bill_type".
 *
 * @property int $id
 * @property string $name
 * @property int $status
 *
 * @property EcommerceBill[] $ecommerceBills
 */
class BillType extends \yii\db\ActiveRecord {

    /**
     * {@inheritdoc}
     */
    public static function tableName() {
        return 'ecommerce_bill_type';
    }

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
            [['status'], 'required'],
            [['status'], 'integer'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => Yii::t('ecommerce', 'ID'),
            'name' => Yii::t('ecommerce', 'Name'),
            'status' => Yii::t('ecommerce', 'Status'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEcommerceBills() {
        return $this->hasMany(EcommerceBill::className(), ['type_id' => 'id']);
    }

    public static function getArray() {

        return ArrayHelper::map(self::find()->all(), 'id', 'name');
    }

}

views/bill/_alert.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

use common\widgets\Alert;
/**
 * Description of _alert
 *
 * @author maxiz
 */
?>
<?= Alert::widget() ?>

views/bill/_form.php
<?php

use yii\helpers\Html;
use kartik\form\ActiveForm;
use codigowww\yii2ecommerce\models\Bill;
use codigowww\yii2ecommerce\models\BillType;
use codigowww\yii2ecommerce\models\PayMethod;
use codigowww\yii2ecommerce\models\Coupon;
use kartik\select2\Select2;
use kartik\number\NumberControl;

/* @var $this yii\web\View */
/* @var $model codigowww\yii2ecommerce\models\Bill */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="bill-form">

    <?php $form = ActiveForm::begin(); ?>


    <div class="row">
        <div class="col-6">

            <?= $this->render('bill-info', ['model' => $billinfo, 'form' => $form]) ?>

        </div>
        <div class="col-6">
             <?= $this->render('bill-items', ['model' => $model,'form' => $form]) ?>
        </div>
        
    </div>
    <div class="row">
        <div class="col-12">

            <div class="card mt-3">
                <div class="card-header bg-primary text-white"><h3 class="card-title"><i class="fas fa-edit"></i><?= Html::encode($this->title) ?></h3></div>

                <div class="card-body">


                    <div class="row">
                        <div class="col-12 col-md-4">
                            <?= $form->field($model, 'user_id')->textInput() ?>
                        </div>
                        <div class="col-12 col-md-4">
                            <?=
                            $form->field($model, 'type_id')->widget(Select2::classname(), [
                                'data' => BillType::getArray(),
                                'options' => ['placeHolder' => ''],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ],
                            ]);
                            ?>
                        </div>
                        <div class="col-12 col-md-4">
                            <?=
                            $form->field($model, 'status')->widget(Select2::classname(), [
                                'data' => [
                                    Bill::STATUS_CREATED => Yii::t('ecommerce', 'Created'),
                                    Bill::STATUS_PENDING => Yii::t('ecommerce', 'Pending'),
                                    Bill::STATUS_SUCCESS => Yii::t('ecommerce', 'Success'),
                                    Bill::STATUS_FAIL => Yii::t('ecommerce', 'Fail'),
                                ],
                                'options' => ['placeholder' => ''],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ],
                            ]);
                            ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <?=
                            $form->field($model, 'payment_method_id')->widget(Select2::classname(), [
                                'data' => PayMethod::getArray(),
                                'options' => ['placeholder' => ''],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ],
                            ]);
                            ?>


                        </div>
                        <div class="col-12 col-md-4">
                            <?= $form->field($model, 'payment_date')->textInput() ?>


                        </div>
                        <div class="col-12 col-md-4">
                            <?= $form->field($model, 'transaction')->textInput(['maxlength' => true]) ?>
                        </div>

                    </div>













                    <div class="row">
                        <div class="col-6">

                            <?= $form->field($model, 'shipping_info')->textarea(['rows' => 6]) ?>
                            <?= $form->field($model, 'note')->textarea(['rows' => 6]) ?>
                        </div>
                        <div class="col-6">
                            <?=
                            $form->field($model, 'subtotal')->widget(NumberControl::classname(), [
                                'maskedInputOptions' => [
                                    'prefix' => '$ ',
                                    'suffix' => '',
                                    'allowMinus' => false
                                ],
                                'options' => [
                                    'type' => 'hidden',
                                    'class' => 'kv-saved',
                                    'readonly' => true,
                                    'tabindex' => 1000
                                ],
                                'displayOptions' => ['class' => 'form-control kv-monospace'],
                                'saveInputContainer' => ['class' => 'kv-saved-cont']
                            ]);
                            ?>
                            <?=
                            $form->field($model, 'shipping')->widget(NumberControl::classname(), [
                                'maskedInputOptions' => [
                                    'prefix' => '$ ',
                                    'suffix' => '',
                                    'allowMinus' => false
                                ],
                                'options' => [
                                    'type' => 'hidden',
                                    'label' => '<label>Saved Value: </label>',
                                    'readonly' => true,
                                    'tabindex' => 1000
                                ],
                                'displayOptions' => ['class' => 'form-control kv-monospace'],
                                'saveInputContainer' => ['class' => 'kv-saved-cont']
                            ]);
                            ?>

                            <?=
                            $form->field($model, 'coupon_id')->widget(Select2::classname(), [
                                'data' => Coupon::getArray(),
                                'options' => ['placeholder' => ''],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ],
                            ]);
                            ?>
                            <?=
                            $form->field($model, 'tax')->widget(NumberControl::classname(), [
                                'maskedInputOptions' => [
                                    'prefix' => '$ ',
                                    'suffix' => '',
                                    'allowMinus' => false
                                ],
                                'options' => [
                                    'type' => 'hidden',
                                    'class' => 'kv-saved',
                                    'readonly' => true,
                                    'tabindex' => 1000
                                ],
                                'displayOptions' => ['class' => 'form-control kv-monospace'],
                                'saveInputContainer' => ['class' => 'kv-saved-cont']
                            ]);
                            ?>
                            <?=
                            $form->field($model, 'total')->widget(NumberControl::classname(), [
                                'maskedInputOptions' => [
                                    'prefix' => '$ ',
                                    'suffix' => '',
                                    'allowMinus' => false
                                ],
                                'options' => [
                                    'type' => 'hidden',
                                    'class' => 'kv-saved',
                                    'readonly' => true,
                                    'tabindex' => 1000
                                ],
                                'displayOptions' => ['class' => 'form-control kv-monospace'],
                                'saveInputContainer' => ['class' => 'kv-saved-cont']
                            ]);
                            ?>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">

                        </div>
                        <div class="col-6">
                            <?=
                            $form->field($model, 'refund')->widget(NumberControl::classname(), [
                                'maskedInputOptions' => [
                                    'prefix' => '$ ',
                                    'suffix' => '',
                                    'allowMinus' => false
                                ],
                                'options' => [
                                    'type' => 'hidden',
                                    'class' => 'kv-saved',
                                    'readonly' => true,
                                    'tabindex' => 1000
                                ],
                                'displayOptions' => ['class' => 'form-control kv-monospace'],
                                'saveInputContainer' => ['class' => 'kv-saved-cont']
                            ]);
                            ?>
                        </div>
                    </div>












                </div>

            </div>


        </div>
    </div>



    <div class="mt-3 text-center">
        <?= Html::submitButton($model->isNewRecord ? '<i class="fas fa-save"></i> ' . Yii::t('ecommerce', 'Guardar') : '<i class="fas fa-save"></i> ' . Yii::t('ecommerce', 'Modificar'), ['class' => $model->isNewRecord ? 'btn btn-success btn-lg px-5' : 'btn btn-success btn-lg px-5']) ?>
    </div>     

    <?php ActiveForm::end(); ?>

</div>

views/bill/bill-info.php
<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>

<?php

use yii\helpers\Html;
use yii\helpers\Url;
use kartik\form\ActiveForm;

/* @var $this yii\web\View */
/* @var $model codigowww\yii2ecommerce\models\BillInfo */
/* @var $form yii\widgets\ActiveForm */
//if (Yii::$app->user->isGuest || (!$model->isNewRecord && !Yii::$app->user->isGuest) ):


$notdisplaybillinfo = !Yii::$app->user->isGuest && $model->isNewRecord && (Yii::$app->request->get('bi') == null || Yii::$app->request->get('bi') > 0) && !empty($billinfo_list);
?> 



<?php if ($notdisplaybillinfo ): ?>
<h4><?= Yii::t('ecommerce', 'Select one preloaded bill info') ?></h4>
<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
    <?php foreach ($billinfo_list as $billinfo): ?>
        <a class="btn btn-dark btn-block btn-lg py-3"  href="<?= Url::toRoute(['/ecommerce/bill/checkout', 'id' => $bill->id, 'bi' => $billinfo->id]) ?>" ><?= $billinfo->f_name . ' ' . $billinfo->l_name ?></a>
    <?php endforeach; ?>
    <a class="btn btn-success btn-block btn-lg py-3"  href="<?= Url::toRoute(['/ecommerce/bill/checkout', 'id' => $bill->id, 'bi' => 0]) ?>" ><?= Yii::t('ecommerce', 'New Bill Info') ?></a>

</div>

<?php endif; ?>

<div class="bill-info-form <?= $notdisplaybillinfo ? 'd-none' : ''?>"> 
    <h4><?= Yii::t('ecommerce', 'Please complete the billing info:') ?></h4>

    <?= Html::hiddenInput('billinfo_id_selected', Yii::$app->request->get('bi') ); ?>
    
    <div class="row">
        <div class="col-12 col-md-4"><?= $form->field($model, 'f_name')->textInput(['maxlength' => true, 'readOnly' => !$model->isNewRecord ]) ?></div>
        <div class="col-12 col-md-4"><?= $form->field($model, 'l_name')->textInput(['maxlength' => true, 'readOnly' => !$model->isNewRecord]) ?></div>
        <div class="col-12 col-md-4"><?= $form->field($model, 'tax_id')->textInput(['maxlength' => true, 'readOnly' => !$model->isNewRecord]) ?></div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">            
            <?= $form->field($model, 'address')->textInput(['maxlength' => true, 'readOnly' => !$model->isNewRecord]) ?>
            <?= $form->field($model, 'address2')->textInput(['maxlength' => true, 'readOnly' => !$model->isNewRecord]) ?>
        </div>
        <div class="col-12 col-md-6">
            <?= $form->field($model, 'email')->textInput(['maxlength' => true, 'readOnly' => !$model->isNewRecord]) ?>
            <?= $form->field($model, 'phone')->textInput(['maxlength' => true, 'readOnly' => !$model->isNewRecord]) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-6 col-md-2"><?= $form->field($model, 'zip')->textInput(['maxlength' => true, 'readOnly' => !$model->isNewRecord]) ?></div>
        <div class="col-6 col-md-3"><?= $form->field($model, 'city')->textInput(['maxlength' => true, 'readOnly' => !$model->isNewRecord]) ?></div>
        <div class="col-6 col-md-3"><?= $form->field($model, 'state')->textInput(['maxlength' => true, 'readOnly' => !$model->isNewRecord]) ?></div>
        <div class="col-6 col-md-4"><?= $form->field($model, 'country')->textInput(['maxlength' => true, 'readOnly' => !$model->isNewRecord]) ?></div>

    </div>





</div> 

views/bill/bill-items.php
<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

use kartik\builder\TabularForm;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;

$billitems = $model->billItems; // where `id` is your primary key
/* $dataProvider = new ActiveDataProvider([
  'query' => $query,
  ]); */
?>

<div class="card">

    <div class="card-header bg-primary text-white"><h3 class="card-title"><?= Yii::t('ecommerce', 'Bill Items') ?></h3></div>
    <div class="card-body">



        <div class="row mb-2">
            <div class="col-3"><?= Yii::t('ecommerce', 'Name') ?></div>
            <div class="col-3"><?= Yii::t('ecommerce', 'Price') ?></div>
            <div class="col-3"><?= Yii::t('ecommerce', 'Quantity') ?></div>
            <div class="col-3"><?= Yii::t('ecommerce', 'Action') ?></div>
        </div>

        <div class="bill-items">

            <?php
            $i = 0;
            foreach ($billitems as $billitem):
                ?>

                <div class="row">
                    <input type="hidden" name="BillItem[<?= $i ?>][id]" value="<?= $billitem->id ?>">
                    <input type="hidden" name="BillItem[<?= $i ?>][remove]" class="remove-input" value="0">
                    <div class="col-3"><input type="text" name="BillItem[<?= $i ?>][name]" class="form-control" value="<?= $billitem->name ?>"></div>
                    <div class="col-3"><input type="number" name="BillItem[<?= $i ?>][price]" class="form-control" value="<?= $billitem->price ?>"></div>
                    <div class="col-3"><input type="text" name="BillItem[<?= $i ?>][quantity]" class="form-control" value="<?= $billitem->quantity ?>"></div>
                    <div class="col-3"><button type="button" class="btn btn-danger btn-remove-item"><i class="fas fa-trash"></i></button></div>
                </div>
                <?php
                $i++;
            endforeach;
            ?>

            <input type="hidden" class="items-count" name="items-count" value="<?= $i - 1 ?>">
        </div>
        <button class="btn btn-success btn-block btn-new-item mt-3" type="button"><?= Yii::t('ecommerce', 'Add Item'); ?></button>

        <div class="templateitem d-none">
            <div class="row mt-1">
                <input type="hidden" name="BillItem[{nrow}][id]" value="">
                <input type="hidden" name="BillItem[{nrow}][remove]" class="remove-input" value="0">
                <div class="col-3"><input type="text" name="BillItem[{nrow}][name]" class="form-control" value=""></div>
                <div class="col-3"><input type="number" name="BillItem[{nrow}][price]" class="form-control" value=""></div>
                <div class="col-3"><input type="text" name="BillItem[{nrow}][quantity]" class="form-control" value=""></div>
                <div class="col-3"><button type="button" class="btn btn-danger btn-remove-item"><i class="fas fa-trash"></i></button></div>
            </div>
        </div>

    </div>

</div>



<?php
$this->registerJs(
        <<<JS
        
        $(".btn-new-item").click(function(){
            var templateitem = $('.templateitem');
            var itemscount = parseInt($('.items-count').val()) + 1;
            var elementappend = templateitem.html().replace(/{nrow}/g, itemscount )
            $('.bill-items').append(elementappend);
             $('.items-count').val(itemscount);
        });

        $(".bill-items").on('click','.btn-remove-item',function(){
            var removeinput = $(this).siblings(".remove-input");
            removeinput.val(1);
            $(this).closest(".row").addClass("d-none");
        });
JS
);
?>

views/bill/view.php
<?php

use yii\helpers\Html;
use kartik\detail\DetailView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model codigowww\yii2ecommerce\models\Bill */

$this->title = $model->id;

$this->params['breadcrumbs'][] = ['label' => Yii::t('ecommerce', 'Bills'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id];
?>



<div class="card">
    <div class="card-header">
        <h3 class="card-title d-inline-block mr-3"> <?= Yii::t('ecommerce', 'Invoice') . ' ' . $this->title ?></h3>
        <strong><?= $model->created_at ?></strong>
        <span class="float-right"> <strong><?= Yii::t('ecommerce', 'Status') ?>:</strong> <?= $model->statusText ?></span>

    </div>
    <div class="card-body">
        <div class="row mb-4">
            <div class="col-sm-6">
                <h6 class="mb-3"><?= Yii::t('ecommerce', 'From') ?>:</h6>
                <div>
                    <strong>Webz Poland</strong>
                </div>
                <div>Madalinskiego 8</div>
                <div>71-101 Szczecin, Poland</div>
                <div>Email: info@webz.com.pl</div>
                <div>Phone: +48 444 666 3333</div>
            </div>

            <div class="col-sm-6">
                <h6 class="mb-3"><?= Yii::t('ecommerce', 'To') ?>:</h6>
                <?php if ($model->billInfo): ?>
                    <div>
                        <strong><?= $model->billInfo->f_name . ' ' . $model->billInfo->l_name ?></strong>
                    </div>
                    <div>Attn: Daniel Marek</div>
                    <div><?= $model->billInfo->address ?></div>
                    <?= $model->billInfo->address2 ? '<div>' . $model->billInfo->address . '</div>' : '' ?>
                    <div>Email: <?= $model->billInfo->email ?></div>
                    <div>Phone: <?= $model->billInfo->phone ?></div>
                <?php endif; ?>
            </div>



        </div>
        <div class="row">
            <div class="col-6">
                <?= $model->note ?>
            </div>
            <div class="col-6">
                <?= $model->shipping_info ?>
            </div>
        </div>
        <?= $this->render('invoice',['model' => $model,'billitems_dataProvider' => $billitems_dataProvider])?>

    </div>
</div>


<div class="text-center mt-3">
    <a class="btn btn-info" href="<?= Url::toRoute(['/ecommerce/bill/view','id' => $model->id,'print' => true]) ?>" ><i class="fas fa-print"></i> <?= Yii::t('ecommerce', 'Print') ?></a>
</div>

<?php if (isset($print) && $print): ?>
    <script>
        window.print();
    </script>
<?php endif; ?>